version: 0.2

phases:
  build:
    commands:
      - echo "Build"
      - mvn clean package
  post_build:
    commands:
      - echo "Post_build"
artifacts:
  files:
    target/HelloWorld
  discard-paths: yes